"""
mode_selector.py

Instrument-specific generation settings.

MIDI playable range is NOT hardcoded here. When the caller knows this
specific recording's own detected pitch (source_f0_hz), the range is
centered on THAT -- see _range_start_from_f0 -- so rendered notes stay
close to what was actually learned instead of a class-wide average.
Otherwise it falls back to models/class_ranges.json, generated by
train_classifier.py from each class's own audio (see
estimate_class_pitch_range there; re-run train_classifier.py whenever
data/ changes so that fallback stays current).

Synthesis presets (mode_name/train_args/render_args/postprocess) ARE looked
up by class name below, but any class without an entry -- e.g. a brand new
instrument folder that hasn't been hand-tuned yet -- automatically falls
back to DEFAULT_PRESET instead of raising, so "add a data/ folder, retrain"
is enough to get a working (if not perfectly tuned) result.
"""

import json
import math
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
CLASS_RANGES_PATH = PROJECT_ROOT / "models" / "class_ranges.json"

DEFAULT_START_MIDI = 48  # C3
DEFAULT_RANGE_COUNT = 36  # 3 octaves, C3-B5

# Matches train_classifier.py's own floor (see its PITCH_RANGE_MIN_START_MIDI
# comment) -- below this, real instruments essentially don't go, and DDSP
# resynthesis extrapolation becomes unreliable.
PITCH_RANGE_MIN_START_MIDI = 24  # C1


def _range_start_from_f0(f0_hz: float, count: int = DEFAULT_RANGE_COUNT) -> int | None:
    """
    C-aligned window start for `count` notes centered on f0_hz -- same
    snap-to-C, floor-clamped math as train_classifier.py's
    estimate_class_pitch_range, applied to this one recording's own pitch
    instead of a class-wide median, so the range stays close to what was
    actually learned.
    """
    if f0_hz is None or f0_hz <= 0:
        return None
    median_midi = 69.0 + 12.0 * math.log2(f0_hz / 440.0)
    approx_start = median_midi - count / 2.0
    start = int(round(approx_start / 12.0)) * 12
    return max(start, PITCH_RANGE_MIN_START_MIDI)


def make_range(start_midi: int, count: int = 36) -> list[int]:
    """
    Generate a consecutive MIDI-note range.

    Example:
        make_range(24) -> MIDI 24-59, C1-B3, 36 notes
    """
    return list(range(start_midi, start_midi + count))


def _load_class_ranges() -> dict:
    if not CLASS_RANGES_PATH.exists():
        return {}
    try:
        with open(CLASS_RANGES_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}


def _midi_notes_for_class(
    predicted_class: str, source_f0_hz: float | None = None
) -> list[int]:
    # Prefer anchoring to what THIS recording actually sounds like over
    # the class-wide range -- see _range_start_from_f0's docstring.
    if source_f0_hz is not None:
        start = _range_start_from_f0(source_f0_hz, DEFAULT_RANGE_COUNT)
        if start is not None:
            return make_range(start, DEFAULT_RANGE_COUNT)

    ranges = _load_class_ranges()
    entry = ranges.get(predicted_class)

    # A missing entry falls back to the default range below -- a malformed
    # entry (e.g. an interrupted write from a crashed train_classifier.py
    # run) should get the same graceful fallback instead of crashing here.
    if not isinstance(entry, dict) or "start_midi" not in entry or "count" not in entry:
        return make_range(DEFAULT_START_MIDI, DEFAULT_RANGE_COUNT)

    return make_range(entry["start_midi"], entry["count"])


# Synthesis presets grouped by attack character: BOWED, WIND, PIANO,
# ORGAN, GUITAR/BASS_GUITAR. DEFAULT_PRESET is the fallback.
BOWED_TRAIN_ARGS = {
    "steps": 7000,
    "residual_strength": 0.15,
    "transient_energy_weight": 1.5,
    "transient_late_weight": 1.5,
    "transient_smooth_weight": 0.15,
    # Wider than train_timbre.py's default (7/9 frames) -- reduces envelope
    # jitter ("shaking") in sustained tones, verified on real cello audio.
    "amp_smooth_kernel": 21,
    "harmonic_smooth_kernel": 21,
}
BOWED_RENDER_ARGS = {"transient_gain": 0.4}

WIND_TRAIN_ARGS = {
    "steps": 7000,
    "residual_strength": 0.20,
    "transient_energy_weight": 1.0,
    "transient_late_weight": 1.0,
    "transient_smooth_weight": 0.08,
    # Same envelope-smoothing fix as BOWED_TRAIN_ARGS -- wind/brass is also
    # a sustained tone, not a plucked/struck attack.
    "amp_smooth_kernel": 21,
    "harmonic_smooth_kernel": 21,
}
WIND_RENDER_ARGS = {"transient_gain": 0.6}

PIANO_TRAIN_ARGS = {
    "steps": 7000,
    "residual_strength": 0.12,
    "transient_energy_weight": 0.8,
    "transient_late_weight": 1.0,
    "transient_smooth_weight": 0.10,
    # Same envelope-smoothing fix as BOWED_TRAIN_ARGS, verified on real
    # piano audio.
    "amp_smooth_kernel": 21,
    "harmonic_smooth_kernel": 21,
}
PIANO_RENDER_ARGS = {"transient_gain": 0.8}
# acoustic_piano only -- not shared with electric_piano/synth, which
# should stay clean/pure. A/B-tested by ear, confirmed closer to a real
# piano than the old pure-harmonic render.
ACOUSTIC_PIANO_RENDER_ARGS = {
    "transient_gain": 0.8,
    "inharmonicity": 0.0006,
    "unison_voices": 3,
    "unison_detune_cents": 1.2,
}

ORGAN_TRAIN_ARGS = {
    "steps": 7000,
    "residual_strength": 0.10,
    "transient_energy_weight": 2.5,
    "transient_late_weight": 2.5,
    "transient_smooth_weight": 0.05,
}
ORGAN_RENDER_ARGS = {"transient_gain": 0.1}

GUITAR_TRAIN_ARGS = {
    "steps": 7000,
    "residual_strength": 0.25,
    "transient_energy_weight": 2.0,
    "transient_late_weight": 2.0,
    "transient_smooth_weight": 0.05,
}
GUITAR_RENDER_ARGS = {"transient_gain": 1.5}

BASS_GUITAR_TRAIN_ARGS = {
    "steps": 7000,
    "residual_strength": 0.40,
    "transient_energy_weight": 6.0,
    "transient_late_weight": 6.0,
    "transient_smooth_weight": 0.02,
}
BASS_GUITAR_RENDER_ARGS = {"transient_gain": 2.0}

DEFAULT_TRAIN_ARGS = {
    "steps": 7000,
    "residual_strength": 0.20,
    "transient_energy_weight": 1.5,
    "transient_late_weight": 1.5,
    "transient_smooth_weight": 0.08,
}
DEFAULT_RENDER_ARGS = {"transient_gain": 1.0}

NO_CLICK = {"bass_click": False, "click_amount": 0.0}
BASS_CLICK = {"bass_click": True, "click_amount": 0.08}

DEFAULT_PRESET = {
    "mode_name": "default_mode",
    "train_args": DEFAULT_TRAIN_ARGS,
    "render_args": DEFAULT_RENDER_ARGS,
    "postprocess": NO_CLICK,
    "vocoder_hybrid": False,
}

# vocoder_hybrid gates render_notes.py's WORLD-vocoder path (see
# VOCODER_MAX_SEMITONES) -- only sounds right for a continuous sustained
# tone. Never enable for plucked/struck instruments: pitch tracking goes
# unstable on the attack, producing an audible warble.
_BOWED = {
    "train_args": BOWED_TRAIN_ARGS,
    "render_args": BOWED_RENDER_ARGS,
    "postprocess": NO_CLICK,
    "vocoder_hybrid": True,
}
_WIND = {
    "train_args": WIND_TRAIN_ARGS,
    "render_args": WIND_RENDER_ARGS,
    "postprocess": NO_CLICK,
    "vocoder_hybrid": True,
}
_PIANO = {
    "train_args": PIANO_TRAIN_ARGS,
    "render_args": PIANO_RENDER_ARGS,
    "postprocess": NO_CLICK,
    "vocoder_hybrid": False,
}
_ORGAN = {
    "train_args": ORGAN_TRAIN_ARGS,
    "render_args": ORGAN_RENDER_ARGS,
    "postprocess": NO_CLICK,
    "vocoder_hybrid": False,
}
_GUITAR = {
    "train_args": GUITAR_TRAIN_ARGS,
    "render_args": GUITAR_RENDER_ARGS,
    "postprocess": NO_CLICK,
    "vocoder_hybrid": False,
}
_BASS_GUITAR = {
    "train_args": BASS_GUITAR_TRAIN_ARGS,
    "render_args": BASS_GUITAR_RENDER_ARGS,
    "postprocess": BASS_CLICK,
    "vocoder_hybrid": False,
}

PRESETS = {
    # strings (bowed)
    "violin": {"mode_name": "violin_mode", **_BOWED},
    "viola": {"mode_name": "viola_mode", **_BOWED},
    "cello": {"mode_name": "cello_mode", **_BOWED},
    "double_bass": {"mode_name": "double_bass_mode", **_BOWED},
    # woodwinds
    "flute": {"mode_name": "flute_mode", **_WIND},
    "oboe": {"mode_name": "oboe_mode", **_WIND},
    "clarinet": {"mode_name": "clarinet_mode", **_WIND},
    "saxophone": {"mode_name": "saxophone_mode", **_WIND},
    "bassoon": {"mode_name": "bassoon_mode", **_WIND},
    # brass
    "trumpet": {"mode_name": "trumpet_mode", **_WIND},
    "trombone": {"mode_name": "trombone_mode", **_WIND},
    "french_horn": {"mode_name": "french_horn_mode", **_WIND},
    "tuba": {"mode_name": "tuba_mode", **_WIND},
    # keyboard
    "acoustic_piano": {
        "mode_name": "acoustic_piano_mode",
        "train_args": PIANO_TRAIN_ARGS,
        "render_args": ACOUSTIC_PIANO_RENDER_ARGS,
        "postprocess": NO_CLICK,
        "vocoder_hybrid": False,
    },
    "electric_piano": {"mode_name": "electric_piano_mode", **_PIANO},
    "organ": {"mode_name": "organ_mode", **_ORGAN},
    "synth": {"mode_name": "synth_mode", **_PIANO},
    # guitar
    "acoustic_guitar": {"mode_name": "acoustic_guitar_mode", **_GUITAR},
    "electric_guitar": {"mode_name": "electric_guitar_mode", **_GUITAR},
    "electric_bass": {"mode_name": "electric_bass_mode", **_BASS_GUITAR},
}


def get_mode_config(predicted_class: str, source_f0_hz: float | None = None) -> dict:
    preset = PRESETS.get(predicted_class, DEFAULT_PRESET)

    return {
        "mode_name": preset["mode_name"],
        "midi_notes": _midi_notes_for_class(predicted_class, source_f0_hz),
        "train_args": preset["train_args"],
        "render_args": preset["render_args"],
        "postprocess": preset["postprocess"],
        "vocoder_hybrid": preset.get("vocoder_hybrid", False),
    }
